; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv64 -mattr=+xmpe,+f -verify-machineinstrs < %s \
; RUN:     | FileCheck %s

define <16 x i32> @mpe_move_mm(<16 x i32> %source) nounwind {
; CHECK-LABEL: mpe_move_mm:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.mm m8, m8
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x i32> @llvm.riscv.mpe.move.mm.v16i32.v16i32(<16 x i32> %source)
    ret <16 x i32> %0
}

define <16 x i32> @mpe_move_xm(i64 %source) nounwind {
; CHECK-LABEL: mpe_move_xm:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.xm m8, a0
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x i32> @llvm.riscv.mpe.move.xm(i64 %source)
    ret <16 x i32> %0
}

define i64 @mpe_move_zx(<16 x i32> %source) nounwind {
; CHECK-LABEL: mpe_move_zx:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.zx a0, m8
; CHECK-NEXT:    ret
entry:
    %0 = call i64 @llvm.riscv.mpe.move.zx(<16 x i32> %source)
    ret i64 %0
}

define <16 x i32> @mpe_move_zm(<16 x i32> %source) nounwind {
; CHECK-LABEL: mpe_move_zm:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.zm m8, m8
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x i32> @llvm.riscv.mpe.move.zm(<16 x i32> %source)
    ret <16 x i32> %0
}

define <16 x float> @mpe_move_fm(float %source) nounwind {
; CHECK-LABEL: mpe_move_fm:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.fm m8, fa0
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x float> @llvm.riscv.mpe.move.fm(float %source)
    ret <16 x float> %0
}

define float @mpe_move_zf(<16 x float> %source) nounwind {
; CHECK-LABEL: mpe_move_zf:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.zf fa0, m8
; CHECK-NEXT:    ret
entry:
    %0 = call float @llvm.riscv.mpe.move.zf(<16 x float> %source)
    ret float %0
}

define <16 x float> @mpe_move_fz(float %source) nounwind {
; CHECK-LABEL: mpe_move_fz:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.fz m8, fa0
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x float> @llvm.riscv.mpe.move.fz(float %source)
    ret <16 x float> %0
}

define <16 x i32> @mpe_move_mm_mask(<16 x i32> %source, i64 %mask) nounwind {
; CHECK-LABEL: mpe_move_mm_mask:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.xm m0, a0
; CHECK-NEXT:    mmv.mm m8, m8, m0.t
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x i32> @llvm.riscv.mpe.move.mm.mask(<16 x i32> %source, i64 %mask)
    ret <16 x i32> %0
}

define <16 x i32> @mpe_move_xm_mask(i64 %source, i64 %mask) nounwind {
; CHECK-LABEL: mpe_move_xm_mask:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.xm m0, a1
; CHECK-NEXT:    mmv.xm m8, a0, m0.t
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x i32> @llvm.riscv.mpe.move.xm.mask(i64 %source, i64 %mask)
    ret <16 x i32> %0
}

define i64 @mpe_move_zx_mask(<16 x i32> %source, i64 %mask) nounwind {
; CHECK-LABEL: mpe_move_zx_mask:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.xm m0, a0
; CHECK-NEXT:    mmv.zx a0, m8, m0.t
; CHECK-NEXT:    ret
entry:
    %0 = call i64 @llvm.riscv.mpe.move.zx.mask(<16 x i32> %source, i64 %mask)
    ret i64 %0
}

define <16 x i32> @mpe_move_zm_mask(<16 x i32> %source, i64 %mask) nounwind {
; CHECK-LABEL: mpe_move_zm_mask:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.xm m0, a0
; CHECK-NEXT:    mmv.zm m8, m8, m0.t
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x i32> @llvm.riscv.mpe.move.zm.mask(<16 x i32> %source, i64 %mask)
    ret <16 x i32> %0
}

define <16 x float> @mpe_move_fm_mask(float %source, i64 %mask) nounwind {
; CHECK-LABEL: mpe_move_fm_mask:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.xm m0, a0
; CHECK-NEXT:    mmv.fm m8, fa0, m0.t
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x float> @llvm.riscv.mpe.move.fm.mask(float %source, i64 %mask)
    ret <16 x float> %0
}

define float @mpe_move_zf_mask(<16 x float> %source, i64 %mask) nounwind {
; CHECK-LABEL: mpe_move_zf_mask:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.xm m0, a0
; CHECK-NEXT:    mmv.zf fa0, m8, m0.t
; CHECK-NEXT:    ret
entry:
    %0 = call float @llvm.riscv.mpe.move.zf.mask(<16 x float> %source, i64 %mask)
    ret float %0
}

define <16 x float> @mpe_move_fz_mask(float %source, i64 %mask) nounwind {
; CHECK-LABEL: mpe_move_fz_mask:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.xm m0, a0
; CHECK-NEXT:    mmv.fz m8, fa0, m0.t
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x float> @llvm.riscv.mpe.move.fz.mask(float %source, i64 %mask)
    ret <16 x float> %0
}
