; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv64 -mattr=+xmpe,+f -verify-machineinstrs < %s \
; RUN:     | FileCheck %s

define <16 x i32> @mpe_add_i32(<16 x i32> %lhs, <16 x i32> %rhs) nounwind {
; CHECK-LABEL: mpe_add_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    madd m8, m8, m9
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x i32> @llvm.riscv.mpe.add.i32(
        <16 x i32> %lhs,
        <16 x i32> %rhs)
    ret <16 x i32> %0
}

define <16 x i32> @mpe_sub_i32(<16 x i32> %lhs, <16 x i32> %rhs) nounwind {
; CHECK-LABEL: mpe_sub_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    msub m8, m8, m9
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x i32> @llvm.riscv.mpe.sub.i32(
        <16 x i32> %lhs,
        <16 x i32> %rhs)
    ret <16 x i32> %0
}

define <16 x i32> @mpe_mac_i32(<16 x i32> %lhs, <16 x i32> %rhs, <16 x i32> %acc) nounwind {
; CHECK-LABEL: mpe_mac_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmac m10, m8, m9
; CHECK-NEXT:    mmv.mm m8, m10
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x i32> @llvm.riscv.mpe.mac.i32(
        <16 x i32> %lhs,
        <16 x i32> %rhs,
        <16 x i32> %acc)
    ret <16 x i32> %0
}

define <16 x float> @mpe_add_f32(<16 x float> %lhs, <16 x float> %rhs) nounwind {
; CHECK-LABEL: mpe_add_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    maddf m8, m8, m9
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x float> @llvm.riscv.mpe.add.f32(
        <16 x float> %lhs,
        <16 x float> %rhs)
    ret <16 x float> %0
}

define <16 x float> @mpe_sub_f32(<16 x float> %lhs, <16 x float> %rhs) nounwind {
; CHECK-LABEL: mpe_sub_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    msubf m8, m8, m9
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x float> @llvm.riscv.mpe.sub.f32(
        <16 x float> %lhs,
        <16 x float> %rhs)
    ret <16 x float> %0
}

define <16 x float> @mpe_mac_f32(<16 x float> %lhs, <16 x float> %rhs, <16 x float> %acc) nounwind {
; CHECK-LABEL: mpe_mac_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmacf m10, m8, m9
; CHECK-NEXT:    mmv.mm m8, m10
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x float> @llvm.riscv.mpe.mac.f32(
        <16 x float> %lhs,
        <16 x float> %rhs,
        <16 x float> %acc)
    ret <16 x float> %0
}

define <16 x i32> @mpe_add_i32_mask(<16 x i32> %lhs, <16 x i32> %rhs, i64 %mask) nounwind {
; CHECK-LABEL: mpe_add_i32_mask:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.xm m0, a0
; CHECK-NEXT:    madd m8, m8, m9, m0.t
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x i32> @llvm.riscv.mpe.add.i32.mask(
        <16 x i32> %lhs,
        <16 x i32> %rhs,
        i64 %mask)
    ret <16 x i32> %0
}

define <16 x i32> @mpe_sub_i32_mask(<16 x i32> %lhs, <16 x i32> %rhs, i64 %mask) nounwind {
; CHECK-LABEL: mpe_sub_i32_mask:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.xm m0, a0
; CHECK-NEXT:    msub m8, m8, m9, m0.t
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x i32> @llvm.riscv.mpe.sub.i32.mask(
        <16 x i32> %lhs,
        <16 x i32> %rhs,
        i64 %mask)
    ret <16 x i32> %0
}

define <16 x i32> @mpe_mac_i32_mask(<16 x i32> %lhs, <16 x i32> %rhs, <16 x i32> %acc, i64 %mask) nounwind {
; CHECK-LABEL: mpe_mac_i32_mask:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.xm m0, a0
; CHECK-NEXT:    mmac m10, m8, m9, m0.t
; CHECK-NEXT:    mmv.mm m8, m10
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x i32> @llvm.riscv.mpe.mac.i32.mask(
        <16 x i32> %lhs,
        <16 x i32> %rhs,
        <16 x i32> %acc,
        i64 %mask)
    ret <16 x i32> %0
}

; CHECK:       mpe_add_f32_mask: # @mpe_add_f32_mask
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.mm m0, m10
; CHECK-NEXT:    maddf m8, m8, m9, m0.t
; CHECK-NEXT:    ret
define <16 x float> @mpe_add_f32_mask(<16 x float> %lhs, <16 x float> %rhs, i64 %mask) nounwind {
; CHECK-LABEL: mpe_add_f32_mask:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.xm m0, a0
; CHECK-NEXT:    maddf m8, m8, m9, m0.t
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x float> @llvm.riscv.mpe.add.f32.mask(
        <16 x float> %lhs,
        <16 x float> %rhs,
        i64 %mask)
    ret <16 x float> %0
}

; CHECK:       mpe_sub_f32_mask: # @mpe_sub_f32_mask
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.mm m0, m10
; CHECK-NEXT:    msubf m8, m8, m9, m0.t
; CHECK-NEXT:    ret
define <16 x float> @mpe_sub_f32_mask(<16 x float> %lhs, <16 x float> %rhs, i64 %mask) nounwind {
; CHECK-LABEL: mpe_sub_f32_mask:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.xm m0, a0
; CHECK-NEXT:    msubf m8, m8, m9, m0.t
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x float> @llvm.riscv.mpe.sub.f32.mask(
        <16 x float> %lhs,
        <16 x float> %rhs,
        i64 %mask)
    ret <16 x float> %0
}

define <16 x float> @mpe_mac_f32_mask(<16 x float> %lhs, <16 x float> %rhs, <16 x float> %acc, i64 %mask) nounwind {
; CHECK-LABEL: mpe_mac_f32_mask:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.xm m0, a0
; CHECK-NEXT:    mmacf m10, m8, m9, m0.t
; CHECK-NEXT:    mmv.mm m8, m10
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x float> @llvm.riscv.mpe.mac.f32.mask(
        <16 x float> %lhs,
        <16 x float> %rhs,
        <16 x float> %acc,
        i64 %mask)
    ret <16 x float> %0
}
