; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv64 -mattr=+xmpe,+f -verify-machineinstrs < %s \
; RUN:     | FileCheck %s

define <16 x i32> @mpe_load_us(ptr %addr) {
; CHECK-LABEL: mpe_load_us:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ml m8, (a0)
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x i32> @llvm.riscv.mpe.load.us.v16i32(ptr %addr)
    ret <16 x i32> %0
}

define <16 x i32> @mpe_load_ss(ptr %addr, i64 %stride) {
; CHECK-LABEL: mpe_load_ss:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlss m8, (a0), a1
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x i32> @llvm.riscv.mpe.load.ss.v16i32(ptr %addr, i64 %stride)
    ret <16 x i32> %0
}

define <16 x i32> @mpe_load_s(ptr %addr, i64 %stride) {
; CHECK-LABEL: mpe_load_s:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mls m8, (a0), a1
; CHECK-NEXT:    ret
entry:
    %0 = call <16 x i32> @llvm.riscv.mpe.load.s.v16i32(ptr %addr, i64 %stride)
    ret <16 x i32> %0
}

; define <16 x i32> @mpe_load_us_mask(ptr %addr, i64 %mask) {
; ; CHECK-LABEL: mpe_load_us_mask
; ; CHECK:       # %bb.0
; ; CHECK-NEXT:    mmv.mm m0, m8
; ; CHECK-NEXT:    ml m8, (a0), m0.t
; ; CHECK-NEXT:    ret
; entry:
;     %0 = tail call <16 x i32> @llvm.riscv.mpe.load.us.mask.v16i32(ptr %addr, i64 %mask)
;     ret <16 x i32> %0
; }

; define <16 x i32> @mpe_load_ss_mask(ptr %addr, i64 %stride, i64 %mask) {
; ; CHECK-LABEL: mpe_load_ss_mask
; ; CHECK:       # %bb.0
; ; CHECK-NEXT:    mmv.mm m0, m8
; ; CHECK-NEXT:    mlss m8, (a0), a1, m0.t
; ; CHECK-NEXT:    ret
; entry:
;     %0 = call <16 x i32> @llvm.riscv.mpe.load.ss.mask.v16i32(ptr %addr, i64 %stride, i64 %mask)
;     ret <16 x i32> %0
; }

; define <16 x i32> @mpe_load_s_mask(ptr %addr, i64 %stride, i64 %mask) {
; ; CHECK-LABEL: mpe_load_s_mask
; ; CHECK:       # %bb.0
; ; CHECK-NEXT:    mmv.mm m0, m8
; ; CHECK-NEXT:    mls m8, (a0), a1, m0.t
; ; CHECK-NEXT:    ret
; entry:
;     %0 = call <16 x i32> @llvm.riscv.mpe.load.s.mask.v16i32(ptr %addr, i64 %stride, i64 %mask)
;     ret <16 x i32> %0
; }
