; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv64 -mattr=+xmpe,+f -verify-machineinstrs < %s \
; RUN:     | FileCheck %s

define void @mpe_store_us(<16 x i32> %m, ptr %addr) {
; CHECK-LABEL: mpe_store_us:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ms m8, (a0)
; CHECK-NEXT:    ret
entry:
    call void @llvm.riscv.mpe.store.us.v16i32(<16 x i32> %m, ptr %addr)
    ret void
}

define void @mpe_store_ss(<16 x i32> %m, ptr %addr, i64 %stride) {
; CHECK-LABEL: mpe_store_ss:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    msss m8, (a0), a1
; CHECK-NEXT:    ret
entry:
    call void @llvm.riscv.mpe.store.ss.v16i32(<16 x i32> %m, ptr %addr, i64 %stride)
    ret void
}

define void @mpe_store_s(<16 x i32> %m, ptr %addr, i64 %stride) {
; CHECK-LABEL: mpe_store_s:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mss m8, (a0), a1
; CHECK-NEXT:    ret
entry:
    call void @llvm.riscv.mpe.store.s.v16i32(<16 x i32> %m, ptr %addr, i64 %stride)
    ret void
}

define void @mpe_store_us_mask(<16 x i32> %m, ptr %addr, i64 %mask) {
; CHECK-LABEL: mpe_store_us_mask:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.xm m0, a1
; CHECK-NEXT:    ms m8, (a0), m0.t
; CHECK-NEXT:    ret
entry:
    call void @llvm.riscv.mpe.store.us.mask.v16i32(<16 x i32> %m, ptr %addr, i64 %mask)
    ret void
}

define void @mpe_store_ss_mask(<16 x i32> %m, ptr %addr, i64 %stride, i64 %mask) {
; CHECK-LABEL: mpe_store_ss_mask:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.xm m0, a2
; CHECK-NEXT:    msss m8, (a0), a1, m0.t
; CHECK-NEXT:    ret
entry:
    call void @llvm.riscv.mpe.store.ss.mask.v16i32(<16 x i32> %m, ptr %addr, i64 %stride, i64 %mask)
    ret void
}

define void @mpe_store_s_mask(<16 x i32> %m, ptr %addr, i64 %stride, i64 %mask) {
; CHECK-LABEL: mpe_store_s_mask:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mmv.xm m0, a2
; CHECK-NEXT:    mss m8, (a0), a1, m0.t
; CHECK-NEXT:    ret
entry:
    call void @llvm.riscv.mpe.store.s.mask.v16i32(<16 x i32> %m, ptr %addr, i64 %stride, i64 %mask)
    ret void
}
